### ISSUE TITLE
[BUG] Copy DOI Link button doubling up on base url

### ISSUE THREAD

**Issue by GitBytes** [EMSL-MSC/pacifica-upload-status#260] opened 2019-01-25 07:12 UTC
When I hit the copy DOI link button and copy link to clipboard, I expect for example to get the URL:
https://dx.doi.org/10.25584/data.2018-12.623/1484509

Instead I am getting:
https://dx.doi.org/https://dx.doi.org/10.25584/data.2018-12.623/1484509

**Comment by kauberry** [comment] 2019-01-29 18:10
This is a duplicate of #257. Fixing it from there. =)

**Comment by kauberry** [comment] 2019-01-29 18:11
Merging this fix in with the changes in #257

**Closed by kauberry** 2019-01-29 18:11 UTC
